### ISSUE TITLE
create a short "how to" using abrmd with TPM2 and TSS

### ISSUE THREAD

**Issue by gallegao** [01org/tpm2-abrmd#32]
Hi,
I am trying to use "abrmd" with TPM2.0 and TSS. 
My apologies if this kind of question should not be here but I could not find any information about how to setup abrmd with TPM2.0, running few basic commands of TPM2 Tools.
Thanks
rgds
marcos

**Comment by flihp** [comment]
No worries @gallegao, you're not the first to ask. I'm working on some content for the README and  the wiki. Should have some stuff up tomorrow.

Likely these docs will just point to the right code / files in the integration test harness. Specifically the function that instantiates the tabrmd TCTI module is here: https://github.com/01org/tpm2-abrmd/blob/master/test/integration/context-util.c#L127. After this the instantiated TCTI context can be passed to the SAPI like it was any other TCTI. Is this generally what you're looking for?

**Comment by flihp** [comment]
I just merged #34 which adds man pages at level 7 for the client TCTI library (tcti-tabrmd) and at level 3 for the initialization function. The man page for `tss2_tcti_tabrmd_init` is where you want to start.

I know it's not exactly what you're asking for but it's a start. I'll get cracking on a more thorough page for the wiki but I've gotta get travis-ci and automated static analysis runs going first.

**Comment by gallegao** [comment]
Hi @flihp,
Great! Thanks for the information and link. Yes, i will start look at that.
I am new to TPM2 world and my issues now is to have a basic system configured and ready to start working with TPM2.
Please, correct me if I am missing something on the steps I am following.

1. Linux Machine with TPM2 enabled on BIOS running CentOS 7 (upgraded kernel to 4.11.0)
2. Installed "IBM TPM 2.0" from https://sourceforge.net/projects/ibmswtpm2/
3. Installed "TPM 2.0 TSS" from https://github.com/01org/TPM2.0-TSS
4. Installed "TPM Tools 2.0" from https://github.com/01org/tpm2.0-tools/
5. Installed "TPM2 ABRMD" Daemon from your site https://github.com/01org/tpm2-abrmd

From what I understand those are the required installation in order to start working with TPM2 in Linux.
Once I have those installed and running, I should be able to run some basic TPM2 commands in order to test and make sure my Linux box is ready and configured with TPM2.0. After that I could start writing my TPM2 applications.

6. So, I checked "tpm_tis" and it was loaded correctly:
May 17 14:36:11 localhost kernel: tpm_tis MSFT0101:00: 2.0 TPM (device-id 0xFE, rev-id 2)
**** Note that "tpm_tis" is automatically loaded!! ****

$ ls -als /sys/class/tpm/tpm0/device/
0 drwxr-xr-x.  4 root root    0 May 17 14:36 .
0 drwxr-xr-x. 25 root root    0 May 17 14:36 ..
0 -r--r--r--.  1 root root 4096 May 17 14:44 description
0 lrwxrwxrwx.  1 root root    0 May 17 14:36 driver -> ../../../../bus/acpi/drivers/tpm_tis
0 -r--r--r--.  1 root root 4096 May 17 14:44 hid
0 -r--r--r--.  1 root root 4096 May 17 14:44 modalias
0 -r--r--r--.  1 root root 4096 May 17 14:44 path
0 lrwxrwxrwx.  1 root root    0 May 17 14:44 physical_node -> ../../../platform/MSFT0101:00
0 drwxr-xr-x.  2 root root    0 May 17 14:44 power


$ dmesg | grep -i tpm
[    0.000000] ACPI: TPM2 00000000d80a1c90 00034 (v03        Tpm2Tabl 00000001 AMI  00000000)
[    1.342345] tpm_tis MSFT0101:00: 2.0 TPM (device-id 0xFE, rev-id 2)

7. Then, I started my TPM2 server and it starts listening on port  2322 and the TPM command server on port 2321.
    ./tpm_server

8. Next I checked the "tpm2-abrmd" daemon service:

	$ sudo ls /usr/lib/systemd/system/tpm*
	/usr/lib/systemd/system/tpm2-abrmd.service

	I enabled the service now:
	
	$ sudo systemctl enable tpm2-abrmd.service
	Created symlink from /etc/systemd/system/multi-user.target.wants/tpm2-abrmd.service to /usr/lib/systemd/system/tpm2-abrmd.service.


	Then check the status again:
	$ sudo systemctl status tpm2-abrmd.service
	  
	● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
	   Loaded: loaded (/usr/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: disabled)
	   Active: activating (auto-restart) (Result: resources) since Wed 2017-05-17 15:40:40 EDT; 4s ago

	But now I get the following error:
	   
	May 17 15:40:40 localhost.localdomain systemd[1]: tpm2-abrmd.service failed to run 'start' task: No such file or directory
	May 17 15:40:40 localhost.localdomain systemd[1]: Failed to start TPM2 Access Broker and Resource Management Daemon.
	May 17 15:40:40 localhost.localdomain systemd[1]: Unit tpm2-abrmd.service entered failed state.
	May 17 15:40:40 localhost.localdomain systemd[1]: tpm2-abrmd.service failed.
	May 17 15:40:40 localhost.localdomain systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...

   
9. So, I am not sure if i am missing something here and maybe you can help me. 
   I believe that if we had some kind of guide or document explaning how to setup a basic linux machine, step by step, including TPM2, TSS, TPM2 Tools and abrmd daemon would be great. That would help a lot of people that does not know
   much about TPM2 and would like to learn.
   
   I could write something after I get my system up and running if you thinkg that should be useful. I found some similar instructions but that was only with TMP 1x and using tcsd daemon and trousers package.
   
   Thanks again for your help and time.
   
   marcos

**Comment by lugong** [comment]
Hi @marcos,
You need to add more configurations according to the file /usr/lib/systemd/system/tpm2-abrmd.service.
It requires EnvironmentFile=/etc/default/tpm2-abrmd and you can add an empty file with the correct path and name.
It also retuires User=tss and you add a user tss and use this account to start service. I just crack this and change it to the root user.
After these two configurations, I think you can expect your results.

**Comment by flihp** [comment]
Yeah @gallegao, it looks like you're super close and I think @lugong identified the last bit perfectly. The INSTALL file is out of date and I'm about to update it with the information from this thread. Effectively it looks like we're missing instructions for integrating the tabrmd with the user / dbus policy / systemd service infrastructure on a Linux system.

**Comment by gallegao** [comment]
Hi @flihp, @lugong 
Thanks a lot for your info.
Ok, I tried @lugong suggestions and still the same problem.
I created the tss user and run the daemon command from that shell.
Also, I get the following error message:
sudo systemctl restart tpm2-abrmd.service
Job for tpm2-abrmd.service failed because a configured resource limit was exceeded. See "systemctl status tpm2-abrmd.service" and "journalctl -xe" for details.

Then, when I look for "journalctl -xe", its contents are empty.

My tpm2-abrmd.service file has:

[Unit]
Description=TPM2 Access Broker and Resource management Daemon

[Service]
Type=dbus
Restart=always
RestartSec=5
EnvironmentFile=/etc/default/tpm2-abrmd
BusName=com.intel.tss2.Tabrmd
StandardOutput=syslog
ExecStart=/usr/local/sbin/tpm2-abrmd
User=tss

[Install]
WantedBy=multi-user.target

And I also copied this file to /etc/system/system folder

Thanks again guys,
Rgds
marcos

**Comment by lugong** [comment]
Hi @gallegao,

Can you check the owner and group of /dev/tpm0?
If the configure file tpm-udev.rules has taken effect, it will be 
crw-------. 1 tss tss 10, 224 May 15 13:28 /dev/tpm0

I changed the owner and group to others and executed the command sudo –u tss ./tpm2-abrmd,
it showed the same error as you encountered.
However it is possible that other configurations causes this problem. I am not sure this is the root cause of your problem.

As for the problem with systemctl, can you use the command journalctl -xe to find more useful info?

In my environment I avoid using the directory /usr/local, so I don't have these problems.

**Comment by gallegao** [comment]
Hi @lugong 
Thanks so much, really appreciated the help.
Ok, I changed the rights of my " /dev/tpm0" as you suggested:
[marcos@localhost sbin]$ ls -als /dev/tpm0
0 crw-------. 1 tss tss 10, 224 May 25 08:34 /dev/tpm0

And now I am not getting this error anymore:
** (tpm2-abrmd:21531): WARNING **: failed to initialize device TCTI context: 0xa000a
 ** (tpm2-abrmd:21531): CRITICAL **: TCTI initialization failed: 0xa000a

But still get other errors when I try to ask for 'status' or 'restart' the service. Here is my output to the "journalctl -xe" command:

[marcos@localhost sbin]$ sudo -u tss systemctl restart tpm2-abrmd.service
Job for tpm2-abrmd.service failed because a configured resource limit was exceeded. See "systemctl status tpm2-abrmd.service" and "journalctl -xe" for details.
[marcos@localhost sbin]$ 
[marcos@localhost sbin]$ journalctl -xe
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit aesmd.service has finished starting up.
-- 
-- The start-up result is done.
May 25 08:36:56 localhost.localdomain aesm_service[1154]: SGX Service unavailable
May 25 08:36:56 localhost.localdomain aesm_service[1154]: Fail to start service.
May 25 08:36:56 localhost.localdomain systemd[1]: aesmd.service: main process exited, code=exited, status=1/FAILURE
May 25 08:36:56 localhost.localdomain systemd[1]: Unit aesmd.service entered failed state.
May 25 08:36:56 localhost.localdomain systemd[1]: aesmd.service failed.
May 25 08:36:58 localhost.localdomain systemd[1]: tpm2-abrmd.service holdoff time over, scheduling restart.
May 25 08:36:58 localhost.localdomain systemd[1]: Failed to load environment files: No such file or directory
May 25 08:36:58 localhost.localdomain systemd[1]: tpm2-abrmd.service failed to run 'start' task: No such file or directory
May 25 08:36:58 localhost.localdomain systemd[1]: Failed to start TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has failed.
-- 
-- The result is failed.
May 25 08:36:58 localhost.localdomain systemd[1]: Unit tpm2-abrmd.service entered failed state.
May 25 08:36:58 localhost.localdomain systemd[1]: tpm2-abrmd.service failed.
May 25 08:36:58 localhost.localdomain systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has begun starting up.
May 25 08:36:58 localhost.localdomain systemd[1]: Couldn't stat device /dev/isgx
May 25 08:37:03 localhost.localdomain systemd[1]: tpm2-abrmd.service holdoff time over, scheduling restart.
May 25 08:37:03 localhost.localdomain systemd[1]: Failed to load environment files: No such file or directory
May 25 08:37:03 localhost.localdomain systemd[1]: tpm2-abrmd.service failed to run 'start' task: No such file or directory
May 25 08:37:03 localhost.localdomain systemd[1]: Failed to start TPM2 Access Broker and Resource Management Daemon.
-- Subject: Unit tpm2-abrmd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has failed.
-- 
-- The result is failed.
May 25 08:37:03 localhost.localdomain systemd[1]: Unit tpm2-abrmd.service entered failed state.
May 25 08:37:03 localhost.localdomain systemd[1]: tpm2-abrmd.service failed.
May 25 08:37:03 localhost.localdomain systemd[1]: Starting TPM2 Access Broker and Resource Management Daemon...
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tpm2-abrmd.service has begun starting up.
lines 2414-2463/2463 (END)

Thanks
Rgds
Marcos

**Comment by flihp** [comment]
Hey @gallegao,

Looks to me like the relevant line is:
````
May 25 08:37:03 localhost.localdomain systemd[1]: Failed to load environment files: No such file or directory
May 25 08:37:03 localhost.localdomain systemd[1]: tpm2-abrmd.service failed to run 'start' task: No such file or directory
````
This was a bug in the old unit file. This line:
```
EnvironmentFile=@sysconfdir@/default/tpm2-abrmd
```
should have been
```
EnvironmentFile=-@sysconfdir@/default/tpm2-abrmd
```
Notice the difference is the `-` preceding the file path. This prevents the failure you're seeing which is caused by the missing environment file. This was fixed in 0f4b7ad47e35c6efb11937769448e7cf30b16cff.

A couple possible fixes:
1. make sure the environment file in your unit file exists (just `touch` the file). It can even be empty.
2. you can add the `-` preceding the path in your unit file
3. you can update to the latest release tag (1.0.0) or the `HEAD` of the `master` branch

Give one (or all) of these a try and let me know how it goes.

**Comment by gallegao** [comment]
Hi @flihp 
Thanks. 
Ok, I got the new version 1.0.0. and installed again. 
Still the same errors but I think you are right, something wrong on my configuration that is probably not loading the environment file.
So, I saw that there are 2 files in "tpm2-abrmd-mater/dist" folder:
_tpm2-abrmd.service.in
tpm2-abrmd.service_

My tpm2-abrmd.service file has:
EnvironmentFile=-**/usr/local/etc**/default/tpm2-abrmd
ExecStart=**/usr/local/sbin/**tpm2-abrmd

My tpm2-abrmd.service.in file has:
EnvironmentFile=-@sysconfdir@/default/tpm2-abrmd
ExecStart=@SBINDIR@/tpm2-abrmd

Do you know what is the difference between these 2 files? Which one should I use?
I looked at /usr/local/etc/ and there is no 'default' folder there.

Thanks again,
Rgds
Marcos

**Comment by flihp** [comment]
Take a look at: https://github.com/01org/tpm2-abrmd/blob/master/Makefile.am#L262

The *service.in file is used to generate the *service file. We just run the .in file through `sed` replacing the @sysconfigdir@ and @sbindir@ strings with some of the variables that automake gets from the configure script. In the end when you install stuff you should only get a *.service file.

The whole thing with the 'default' file looks fine to me. This is used to set distro specific environment for the daemon when systemd starts it up. It is optional so if you haven't created one the daemon will still start, on my development system (Debian stable) it does at least :smile:

**Comment by flihp** [comment]
no motion on this for a while. If you're still having trouble we've worked through a similar / same situation recently here: https://github.com/01org/tpm2-abrmd/issues/92

**Comment by dassanjib** [comment]
Hi @flihp,

I went through this entire email/message chain & tried all steps recommended here.  Unfortunately I still find issue in running tpm2_abrmd daemon [tpm_server is running successfully]. My tpm2-abrmd.service is getting killed.

Took this tar ball
https://github.com/tpm2-software/tpm2-abrmd/releases/tag/2.0.0
tpm2-abrmd-2.0.0.tar.gz


./configure
make
make install

[tpm2-abrmd-2.0.0]ls /etc/udev/rules.d/
tpm-udev.rules

[tpm2-abrmd-2.0.0]sudo systemctl enable tpm2-abrmd.service
[tpm2-abrmd-2.0.0]
[tpm2-abrmd-2.0.0]
[tpm2-abrmd-2.0.0]sudo systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
   Loaded: loaded (/usr/local/lib/systemd/system/tpm2-abrmd.service; enabled; ve
   Active: activating (auto-restart) (Result: signal) since Tue 2018-06-26 12:17
  Process: 20023 ExecStart=/usr/local/sbin/tpm2-abrmd (code=killed, signal=TRAP)
 Main PID: 20023 (code=killed, signal=TRAP)

Jun 26 12:17:20 ubuntu systemd[1]: tpm2-abrmd.service: Main process exited, code
Jun 26 12:17:20 ubuntu systemd[1]: tpm2-abrmd.service: Unit entered failed state
Jun 26 12:17:20 ubuntu systemd[1]: tpm2-abrmd.service: Failed with result 'signa
lines 1-9/9 (END)[ 9049.101241] tpm tpm0: Operation Timed out

[tpm2-abrmd-2.0.0]cat /usr/local/lib/udev/rules.d/tpm-udev.rules
tpm devices can only be accessed by the tss user but the tss
group members can access tpmrm devices

KERNEL=="tpm[0-9]*", MODE="0660", OWNER="tss"
KERNEL=="tpmrm[0-9]*", MODE="0660", OWNER="tss", GROUP="tss"

[tpm2-abrmd-2.0.0]ls -l /dev/tpm0 
crw------- 1 tss tss 10, 224 Jun 26 09:46 /dev/tpm0

[tpm2-abrmd-2.0.0]journalctl -xe
-- Unit tpm2-abrmd.service has finished shutting down.
Jun 26 12:29:03 ubuntu systemd[1]: Starting TPM2 Access Broker and Resource Mana
-- Subject: Unit tpm2-abrmd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit tpm2-abrmd.service has begun starting up.
Jun 26 12:29:04 ubuntu systemd[1]: Started TPM2 Access Broker and Resource Manag
-- Subject: Unit tpm2-abrmd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Unit tpm2-abrmd.service has finished starting up.
-- The start-up result is done.
-- The start-up result is done.
Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ERROR:tcti:src/util/io.c:81:write_all() failed to write to fd 5: Timer expired
Jun 26 12:22:38 ubuntu kernel: tpm tpm0: Operation Timed out
Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ERROR:tcti:src/tss2-tcti/tcti-device.c:85:tcti_device_transmit() wrong number of bytes written. Expected 22, wrote 0.
Jun 26 12:22:38 ubuntu tpm2-abrmd[21561]: ** (tpm2-abrmd:21561): ERROR **: Failed to GetCapability: TPM2_CAP_TPM_PROPERTIES, TPM2_PT_FIXED: 0xa000a
Jun 26 12:22:38 ubuntu kernel: traps: tpm2-abrmd[21562] trap int3 ip:7fce1b7d9a5b sp:7fce19c8bb90 error:0 in libglib-2.0.so.0.4800.2[7fce1b789000+10f000]

[@ubuntu: TSS-TOOL/tpm2-abrmd/tpm2-abrmd] ls -als /sys/class/tpm/tpm0/device/
total 0
0 drwxr-xr-x  5 root root    0 Jun 26 10:27 .
0 drwxr-xr-x 19 root root    0 Jun 26 09:46 ..
0 lrwxrwxrwx  1 root root    0 Jun 26 10:27 driver -> ../../../bus/platform/drivers/tpm_tis
0 -rw-r--r--  1 root root 4096 Jun 26 10:27 driver_override
0 -r--r--r--  1 root root 4096 Jun 26 10:27 modalias
0 drwxr-xr-x  2 root root    0 Jun 26 10:27 power
0 lrwxrwxrwx  1 root root    0 Jun 26 09:46 subsystem -> ../../../bus/platform
0 drwxr-xr-x  3 root root    0 Jun 26 09:46 tpm
0 drwxr-xr-x  3 root root    0 Jun 26 09:46 tpmrm
0 -rw-r--r--  1 root root 4096 Jun 26 09:46 uevent

[@ubuntu: TSS-TOOL/tpm2-abrmd/tpm2-abrmd] dmesg | grep -i tpm_tis
[    3.079658] tpm_tis tpm_tis: 2.0 TPM (device-id 0x3205, rev-id 1)
[tpm2-abrmd-2.0.0]ls /dev/tpm*
/dev/tpm0  /dev/tpmrm0

Not sure if this was seen by others as well, or just happening on my box (kernel-4.14.48) :(
Thanks in advance. You have been always helpful to everyone on any TPM issue.
Appreciate all your help.

Thanks,
Sanjib
